name: Rollback if failure
on: 
  push

jobs:
  call-rollback-if-failure-workflow:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false && startsWith(github.head_ref, 'do_release')
    name: Rollback if failure
    
    steps:
    - name: test
      run: |
        echo "hello"
